import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { describe, it } from "node:test";
import { extractExif, readImageDimensions } from "@/lib/image-metadata";
import { encodeBlurhash } from "@/lib/image-placeholder";

/* --- fixtures ------------------------------------------------------------ */

function png(width: number, height: number): Uint8Array {
  const bytes = new Uint8Array(33);
  bytes.set([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a], 0);
  const view = new DataView(bytes.buffer);
  view.setUint32(8, 13); // IHDR length
  bytes.set([0x49, 0x48, 0x44, 0x52], 12); // "IHDR"
  view.setUint32(16, width);
  view.setUint32(20, height);
  return bytes;
}

function gif(width: number, height: number): Uint8Array {
  const bytes = new Uint8Array(24);
  bytes.set([0x47, 0x49, 0x46, 0x38, 0x39, 0x61], 0); // "GIF89a"
  const view = new DataView(bytes.buffer);
  view.setUint16(6, width, true);
  view.setUint16(8, height, true);
  return bytes;
}

/**
 * A JPEG with a run of metadata segments before the frame header.
 *
 * The padding is the point: JPEG has no fixed offset for its dimensions, so a
 * parser that peeks at a constant position happens to work on files from one
 * camera and silently fails on the next.
 */
function jpeg(width: number, height: number, padding: Uint8Array[] = []): Uint8Array {
  const parts: number[] = [0xff, 0xd8];
  for (const segment of padding) parts.push(...segment);
  parts.push(
    0xff, 0xc0, // SOF0
    0x00, 0x11, // length
    0x08, // precision
    (height >> 8) & 0xff, height & 0xff,
    (width >> 8) & 0xff, width & 0xff,
    0x03,
  );
  while (parts.length < 24) parts.push(0);
  return Uint8Array.from(parts);
}

/** A COM segment of `length` payload bytes, to push the frame header along. */
function comment(length: number): Uint8Array {
  const size = length + 2;
  return Uint8Array.from([0xff, 0xfe, (size >> 8) & 0xff, size & 0xff, ...new Array(length).fill(0x20)]);
}

/** A little-endian APP1 segment carrying one IFD0 entry. */
function exifSegment(
  entries: { tag: number; type: number; count: number; value: number }[],
): Uint8Array {
  const tiff: number[] = [
    0x49, 0x49, // "II" — little-endian
    0x2a, 0x00,
    0x08, 0x00, 0x00, 0x00, // IFD0 at offset 8
    entries.length & 0xff, (entries.length >> 8) & 0xff,
  ];
  for (const entry of entries) {
    tiff.push(
      entry.tag & 0xff, (entry.tag >> 8) & 0xff,
      entry.type & 0xff, (entry.type >> 8) & 0xff,
      entry.count & 0xff, (entry.count >> 8) & 0xff, 0, 0,
      entry.value & 0xff, (entry.value >> 8) & 0xff,
      (entry.value >> 16) & 0xff, (entry.value >> 24) & 0xff,
    );
  }
  tiff.push(0, 0, 0, 0); // No next IFD.

  const payload = [0x45, 0x78, 0x69, 0x66, 0x00, 0x00, ...tiff]; // "Exif\0\0"
  const size = payload.length + 2;
  return Uint8Array.from([0xff, 0xe1, (size >> 8) & 0xff, size & 0xff, ...payload]);
}

/** A string value stored out of line, with the entry pointing at it. */
function exifWithString(tag: number, text: string): Uint8Array {
  const bytes = [...new TextEncoder().encode(text), 0];
  const tiff: number[] = [
    0x49, 0x49, 0x2a, 0x00,
    0x08, 0x00, 0x00, 0x00,
    0x01, 0x00,
    tag & 0xff, (tag >> 8) & 0xff,
    0x02, 0x00, // ASCII
    bytes.length & 0xff, (bytes.length >> 8) & 0xff, 0, 0,
    // Offset from the TIFF header: 8 + 2 + 12 + 4.
    0x1a, 0x00, 0x00, 0x00,
    0, 0, 0, 0,
    ...bytes,
  ];
  const payload = [0x45, 0x78, 0x69, 0x66, 0x00, 0x00, ...tiff];
  const size = payload.length + 2;
  return Uint8Array.from([0xff, 0xe1, (size >> 8) & 0xff, size & 0xff, ...payload]);
}

/* --- tests --------------------------------------------------------------- */

describe("image dimensions", () => {
  it("reads a PNG's IHDR", () => {
    assert.deepEqual(readImageDimensions(png(1200, 630)), { width: 1200, height: 630 });
  });

  it("reads a real PNG off disk", async () => {
    // Generated by scripts/generate-og-images.ts at a known 1200×630.
    const bytes = new Uint8Array(await readFile("public/og/default.png"));
    assert.deepEqual(readImageDimensions(bytes), { width: 1200, height: 630 });
  });

  it("reads a GIF's little-endian header", () => {
    assert.deepEqual(readImageDimensions(gif(320, 240)), { width: 320, height: 240 });
  });

  it("walks JPEG segments to find the frame header", () => {
    assert.deepEqual(readImageDimensions(jpeg(4032, 3024)), { width: 4032, height: 3024 });
  });

  it("finds it past a long run of metadata", () => {
    const padded = jpeg(800, 600, [comment(400), comment(120)]);
    assert.deepEqual(readImageDimensions(padded), { width: 800, height: 600 });
  });

  it("skips a Huffman table rather than reading it as a frame", () => {
    // 0xC4 sits inside the SOFn range but is a table, not a frame. Reading it
    // as one yields dimensions out of the middle of the Huffman data.
    const table = Uint8Array.from([0xff, 0xc4, 0x00, 0x08, 1, 2, 3, 4, 5, 6]);
    assert.deepEqual(readImageDimensions(jpeg(640, 480, [table])), {
      width: 640,
      height: 480,
    });
  });

  it("gives up cleanly at the start of scan data", () => {
    const scan = Uint8Array.from([0xff, 0xda, 0x00, 0x0c, ...new Array(10).fill(0)]);
    const bytes = Uint8Array.from([0xff, 0xd8, ...scan, ...new Array(20).fill(0)]);
    assert.equal(readImageDimensions(bytes), null);
  });

  it("reads all three WebP variants", () => {
    const riff = (chunk: string, rest: number[]) =>
      Uint8Array.from([
        ...new TextEncoder().encode("RIFF"),
        0, 0, 0, 0,
        ...new TextEncoder().encode("WEBP"),
        ...new TextEncoder().encode(chunk),
        ...rest,
      ]);

    // VP8X: 24-bit little-endian, stored as (dimension - 1).
    const extended = riff("VP8X", [0, 0, 0, 0, 0, 0, 0, 0, 0x1f, 0x02, 0x00, 0x8b, 0x01, 0x00]);
    assert.deepEqual(readImageDimensions(extended), { width: 544, height: 396 });

    // VP8: 14-bit fields; the top two bits are a scaling factor.
    const lossy = riff("VP8 ", [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0x40, 0x81, // 320, with scale bits set
      0xf0, 0x40, // 240
    ]);
    assert.deepEqual(readImageDimensions(lossy), { width: 320, height: 240 });

    const lossless = riff("VP8L", [0, 0, 0, 0, 0x2f, 0x3f, 0x00, 0xc0, 0x3b]);
    const size = readImageDimensions(lossless);
    assert.ok(size && size.width > 0 && size.height > 0);
  });

  it("returns null rather than guessing at something it cannot read", () => {
    assert.equal(readImageDimensions(new Uint8Array(4)), null);
    assert.equal(readImageDimensions(Uint8Array.from(new Array(40).fill(0x41))), null);
  });
});

describe("EXIF", () => {
  const ORIENTATION = 0x0112;
  const ISO = 0x8827;
  const MAKE = 0x010f;

  it("reads orientation and ISO out of IFD0", () => {
    const bytes = Uint8Array.from([
      0xff, 0xd8,
      ...exifSegment([
        { tag: ORIENTATION, type: 3, count: 1, value: 6 },
        { tag: ISO, type: 3, count: 1, value: 400 },
      ]),
      ...jpeg(100, 100).slice(2),
    ]);

    const exif = extractExif(bytes);
    assert.equal(exif?.orientation, 6);
    assert.equal(exif?.iso, 400);
  });

  it("reads a string stored out of line", () => {
    const bytes = Uint8Array.from([0xff, 0xd8, ...exifWithString(MAKE, "FUJIFILM")]);
    assert.equal(extractExif(bytes)?.make, "FUJIFILM");
  });

  it("never reads GPS, even when the file carries it", () => {
    // 0x8825 is the GPS IFD pointer. A photo from a phone routinely has one,
    // and the coordinates in it are of the house it was taken in.
    const bytes = Uint8Array.from([
      0xff, 0xd8,
      ...exifSegment([
        { tag: 0x8825, type: 4, count: 1, value: 200 },
        { tag: ORIENTATION, type: 3, count: 1, value: 1 },
      ]),
    ]);

    const exif = extractExif(bytes);
    assert.equal(exif?.orientation, 1);
    assert.ok(!JSON.stringify(exif).toLowerCase().includes("gps"));
    assert.deepEqual(Object.keys(exif ?? {}), ["orientation"]);
  });

  it("returns null for a file with no EXIF rather than throwing", () => {
    assert.equal(extractExif(jpeg(100, 100)), null);
    assert.equal(extractExif(png(10, 10)), null);
    assert.equal(extractExif(new Uint8Array(2)), null);
  });

  it("survives a truncated segment", () => {
    const segment = exifSegment([{ tag: ORIENTATION, type: 3, count: 1, value: 3 }]);
    const truncated = Uint8Array.from([0xff, 0xd8, ...segment.slice(0, 12)]);
    assert.doesNotThrow(() => extractExif(truncated));
  });

  it("rewrites an EXIF timestamp into something Date can parse", () => {
    const DATE_TIME_ORIGINAL = 0x9003;
    const bytes = Uint8Array.from([
      0xff, 0xd8,
      ...exifWithString(DATE_TIME_ORIGINAL, "2026:08:30 14:22:07"),
    ]);
    const taken = extractExif(bytes)?.taken_at;
    assert.equal(taken, "2026-08-30 14:22:07");
    assert.ok(!Number.isNaN(new Date(taken!).getTime()), "still unparseable");
  });
});

describe("BlurHash", () => {
  function solid(width: number, height: number, rgb: [number, number, number]) {
    const pixels = new Uint8ClampedArray(width * height * 4);
    for (let index = 0; index < width * height; index += 1) {
      pixels[index * 4] = rgb[0];
      pixels[index * 4 + 1] = rgb[1];
      pixels[index * 4 + 2] = rgb[2];
      pixels[index * 4 + 3] = 255;
    }
    return pixels;
  }

  it("produces a hash of the length the components imply", () => {
    // 1 size flag + 1 maximum + 4 DC + 2 per AC component.
    const hash = encodeBlurhash(solid(8, 8, [255, 0, 0]), 8, 8, 4, 3);
    assert.equal(hash.length, 6 + 2 * (4 * 3 - 1));
  });

  it("encodes the component counts in the first character", () => {
    const hash = encodeBlurhash(solid(4, 4, [0, 0, 0]), 4, 4, 4, 3);
    const flag = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz#$%*+,-.:;=?@[]^_{|}~".indexOf(hash[0]);
    assert.equal((flag % 9) + 1, 4);
    assert.equal(Math.floor(flag / 9) + 1, 3);
  });

  it("gives different colours different hashes", () => {
    const red = encodeBlurhash(solid(4, 4, [255, 0, 0]), 4, 4, 4, 3);
    const blue = encodeBlurhash(solid(4, 4, [0, 0, 255]), 4, 4, 4, 3);
    assert.notEqual(red, blue);
  });

  it("uses only base-83 characters, so the hash is URL and JSON safe", () => {
    const hash = encodeBlurhash(solid(6, 6, [120, 200, 90]), 6, 6, 4, 3);
    assert.match(hash, /^[0-9A-Za-z#$%*+,\-.:;=?@[\]^_{|}~]+$/);
  });
});
